### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by ElijahKaftanov** [herecura/vivaldi-snapshot-ffmpeg-codecs#1]
Can't build vivaldi-snapshot-ffmpeg-codecs.
The output says:

> [4138/5806] gcc -MMD -MF obj/third_party/libjpeg_turbo/libjpeg/jchuff.o.d -DWITH_SIMD -DNO_GETENV -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DNO_TCMALLOC -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DCOMPONENT_BUILD -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -I../../third_party/libjpeg_turbo -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -pthread -m64 -march=x86-64 -Wall -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -fno-delete-null-pointer-checks -Wno-missing-field-initializers -Wno-unused-parameter -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -fvisibility=hidden -std=gnu11 -c ../../third_party/libjpeg_turbo/jchuff.c -o obj/third_party/libjpeg_turbo/libjpeg/jchuff.o
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...

distribution: Manjaro Linux 17.1.2
kernel: 4.14.14-1-MANJARO

Can you please help me?

**Comment by BlackIkeEagle** [comment]
On Sun, Jan 28, 2018 at 09:27:51PM +0000, ElijahKaftanov wrote:
> Can't build vivaldi-snapshot-ffmpeg-codecs.
> The output says:
> 
> > [4138/5806] gcc -MMD -MF obj/third_party/libjpeg_turbo/libjpeg/jchuff.o.d -DWITH_SIMD -DNO_GETENV -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DNO_TCMALLOC -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DCOMPONENT_BUILD -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -I../../third_party/libjpeg_turbo -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -pthread -m64 -march=x86-64 -Wall -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -fno-delete-null-pointer-checks -Wno-missing-field-initializers -Wno-unused-parameter -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -fvisibility=hidden -std=gnu11 -c ../../third_party/libjpeg_turbo/jchuff.c -o obj/third_party/libjpeg_turbo/libjpeg/jchuff.o
> ninja: build stopped: subcommand failed.
> ==> ERROR: A failure occurred in build().
>     Aborting...
> 
> distribution: Manjaro Linux 17.1.2
> kernel: 4.14.14-1-MANJARO
> 
> Can you please help me?
> 

Could you add more of the logging since that line is not where the error
happens.

I'm building in a clean chroot. Maybe you are building directly on your
system where the chromium build script picks up other dependencies not
really needed for the ffmpeg part.

And if you just want to install the libffmpeg.so to have proprietary
codecs, you could also use my repo: https://repo.herecura.be

-- Ike
