### ISSUE TITLE
Latest vivaldi-snapshot stopped working with these codecs

### ISSUE THREAD

**Issue by LeBaux** [herecura/vivaldi-snapshot-ffmpeg-codecs#2]
```
2 herecura/vivaldi-snapshot-ffmpeg-codecs 77.0.3865.93-1 (1.2 MiB 4.2 MiB) (Installed)
    additional support for proprietary codecs for vivaldi
1 herecura/vivaldi-snapshot 2.9.1705.27-1 (63.6 MiB 224.5 MiB) (Installed)
    An advanced browser made with the power user in mind. Snapshot
```
I use these 2 packages from your repo, but today Vivaldi snapshot started acting up with proprietary video codes.

![image](https://user-images.githubusercontent.com/5657511/67766376-94a8e300-fa4e-11e9-8c49-9e49646ced4d.png)

[Test video](https://help.vivaldi.com/article/html5-proprietary-media-on-linux/) is indeed broken. I (still) use Manjaro that you do not support, I just thought this might be a distribution agnostic problem and thought I might as well bring it to your attention.

Thank you for making Vivaldi snapshots available for us!
Cheers, Pierre.

**Comment by BlackIkeEagle** [comment]
Hi @LeBaux ,

I'm aware of the issue, but currently the ffmpeg codecs don't build properly so all I can do is ask you to wait for a while for me to get it working again.

**Comment by LeBaux** [comment]
Thank you for your reply! It is a development version of Vivaldi after all, something was bound to break eventually. Stable version works as expected, I'll use that in the meantime and track this issue for changes.

If you do not mind, can you please clarify one thing? Why `vivaldi-snapshot-ffmpeg-codecs` in `herecura` are prebuilt, but not in AUR? Especially since [stable Vivaldi has prebuilt codecs on AUR](https://aur.archlinux.org/packages/vivaldi-codecs-ffmpeg-extra-bin/).

I do not mind using your repo, it would just seem more convenient to have everything on AUR. I am far from the experienced user, maybe I am missing something obvious here. Hopefully, it is not the dumbest question. Thank you!

**Comment by BlackIkeEagle** [comment]
Hi @LeBaux , the version in aur and my repo should be working now.

And for your other question, AUR is meant to have description of the package to be able to build it from source. for vivaldi someone else provides a package that just installs the ffmpeg.so in the correct location because building from chromium sources takes a long time and is relatively error prone.

**Comment by BlackIkeEagle** [comment]
I'm currently testing with netflix and all seems to work

**Comment by LeBaux** [comment]
Works on my end too, no problems. Thank you for a quick fix and explanation. Cheers!
